name: Cucumber CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test
        continue-on-error: true
        
      - name: rename to index.html
        run: mv build/cucumber-reports/cucumber-html-reports/overview-features.html build/cucumber-reports/cucumber-html-reports/index.html 
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages 
          folder: build/cucumber-reports/cucumber-html-reports/ 
